name: chat_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  fluttertoast: ^8.2.6
  firebase_auth: ^5.1.0
  flutter_riverpod: ^2.5.1
  animated_bottom_navigation_bar: ^1.3.3
  url_launcher: ^6.3.0
  google_generative_ai: ^0.4.3
  flutter_markdown: ^0.7.3
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^3.0.0
  flutter_sticky_header: ^0.6.5
  google_fonts: ^6.2.1
  intl: ^0.19.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/